
#########################################
## CREATE NAMESPACE
#########################################

---

apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cnv



# oc get packagemanifests -n openshift-marketplace
#########################################
## INSTALL OPERATOR
#########################################

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-cnv-
  namespace: openshift-cnv
spec:
  targetNamespaces:
  - openshift-cnv



---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: "${CHANNEL_CNV}"
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
