kind: Template
apiVersion: v1
metadata:
  annotations:
    tags: cnv
  name: cnv2
objects:
#########################################
## create the KubeVirt HyperConverged Cluster Operator Deployment custom resource
#########################################
- kind: HyperConverged
  apiVersion: hco.kubevirt.io/v1alpha1
  metadata:
    name: kubevirt-hyperconverged
    namespace: "${NAMESPACE_CNV}"
  spec:
    BareMetalPlatform: false
parameters:
  - name: NAMESPACE_CNV
    displayName: Namespace for CNV
    description: Namespace for CNV
    required: true
    value: "openshift-cnv"
