# SERVICE ROLE - NAMESPACE SCOPE (services/methods/paths)
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: admin
  namespace: ${NAMESPACE}
spec:
  rules:
  - services: ["*"]
    methods: ["*"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: admin-binding
  namespace: ${NAMESPACE}
spec:
  subjects:
  - user: "cluster.local/ns/${NAMESPACE}/sa/default"
  roleRef:
    kind: ServiceRole
    name: admin
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: ingress-binding
  namespace: ${NAMESPACE}
spec:
  subjects:
  - user: "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
  roleRef:
    kind: ServiceRole
    name: admin
