apiVersion: "istio.openshift.com/v1alpha1"
kind: "Installation"
metadata:
  name: "istio-installation"
  namespace: istio-operator
spec:
  deployment_type: openshift
  istio:
    authentication: true
    community: false
    prefix: openshift-istio-tech-preview/
    version: 0.7.0
  jaeger:
    prefix: distributed-tracing-tech-preview/
    version: 1.9.0
    elasticsearch_memory: 1Gi
  kiali:
    username: admin
    password: admin
    prefix: kiali/
    version: v0.13.0

