apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: level1jwt
spec:
  targets:
  - name: customer
  - name: partner
  peers:
  - mtls:
  origins:
  - jwt:
      issuer: http://keycloak-sso.${SUBDOMAIN}/auth/realms/istio
      jwksUri: http://keycloak-sso.${SUBDOMAIN}/auth/realms/istio/protocol/openid-connect/certs
      audiences:
      - customer-tutorial  
  principalBinding: USE_ORIGIN
