apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denypartnerhandler
  namespace: $NAMESPACE
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denypartnerrequests
  namespace: $NAMESPACE
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denypartner
  namespace: $NAMESPACE
spec:
  match: destination.labels["app"] == "preference" && source.labels["app"]=="customer"
  actions:
  - handler: denypartnerhandler.denier
    instances: [ denypartnerrequests.checknothing ]

